// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uniqueidentifier/stringbased.proto

package info.moetang.serviceprotocol.protobuf.uniqueidentifier;

public interface GenerateStringResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uniqueidentifier.GenerateStringRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string error_message = 2;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 2;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>string unique_identifier = 11;</code>
   * @return The uniqueIdentifier.
   */
  java.lang.String getUniqueIdentifier();
  /**
   * <code>string unique_identifier = 11;</code>
   * @return The bytes for uniqueIdentifier.
   */
  com.google.protobuf.ByteString
      getUniqueIdentifierBytes();
}
