// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uniqueidentifier/integerbased.proto

package info.moetang.serviceprotocol.protobuf.uniqueidentifier;

public interface GenerateIntegerReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uniqueidentifier.GenerateIntegerReq)
    com.google.protobuf.MessageOrBuilder {
}
