// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: countdown/countdown.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Countdown {

  /// <summary>Holder for reflection information generated from countdown/countdown.proto</summary>
  public static partial class CountdownReflection {

    #region Descriptor
    /// <summary>File descriptor for countdown/countdown.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CountdownReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chljb3VudGRvd24vY291bnRkb3duLnByb3RvEgljb3VudGRvd24aE3NoYXJl",
            "ZC9yZXN1bHQucHJvdG8ixgEKCUNvdW50ZG93bhIUCgxjb3VudGRvd25faWQY",
            "ASABKAkSDwoHdXNlcl9pZBgCIAEoCRIWCg5jb3VudGRvd25fdHlwZRgDIAEo",
            "CRINCgV0aXRsZRgLIAEoCRIPCgdjb250ZW50GAwgASgJEhQKDHRpbWVfZXhw",
            "aXJlZBgVIAEoAxIYChB0aW1lX2xhc3RfaGFuZGxlGBYgASgDEhQKDHRpbWVf",
            "Y3JlYXRlZBgXIAEoAxIUCgx0aW1lX3VwZGF0ZWQYGCABKAMicwoSQ3JlYXRl",
            "Q291bnRkb3duUmVxEg8KB3VzZXJfaWQYASABKAkSFgoOY291bnRkb3duX3R5",
            "cGUYAiABKAkSDQoFdGl0bGUYCyABKAkSDwoHY29udGVudBgMIAEoCRIUCgx0",
            "aW1lX2V4cGlyZWQYFSABKAMiXQoSQ3JlYXRlQ291bnRkb3duUmVzEh4KBnJl",
            "c3VsdBgBIAEoCzIOLnNoYXJlZC5SZXN1bHQSJwoJY291bnRkb3duGAIgASgL",
            "MhQuY291bnRkb3duLkNvdW50ZG93biItChVRdWVyeUNvdW50ZG93bkJ5SWRS",
            "ZXESFAoMY291bnRkb3duX2lkGAEgASgJImAKFVF1ZXJ5Q291bnRkb3duQnlJ",
            "ZFJlcxIeCgZyZXN1bHQYASABKAsyDi5zaGFyZWQuUmVzdWx0EicKCWNvdW50",
            "ZG93bhgCIAEoCzIULmNvdW50ZG93bi5Db3VudGRvd24iSgocTmV4dENvdW50",
            "ZG93bkludGVydmFsQnlJZFJlcRIUCgxjb3VudGRvd25faWQYASABKAkSFAoM",
            "dGltZV9leHBpcmVkGAIgASgDImcKHE5leHRDb3VudGRvd25JbnRlcnZhbEJ5",
            "SWRSZXMSHgoGcmVzdWx0GAEgASgLMg4uc2hhcmVkLlJlc3VsdBInCgljb3Vu",
            "dGRvd24YAiABKAsyFC5jb3VudGRvd24uQ291bnRkb3duIl8KJFF1ZXJ5UGFn",
            "ZWRFeHByaW5nQ291bnRkb3duc0J5VHlwZVJlcRIWCg5jb3VudGRvd25fdHlw",
            "ZRgBIAEoCRIMCgRwYWdlGAIgASgDEhEKCXBhZ2Vfc2l6ZRgDIAEoAyJwCiRR",
            "dWVyeVBhZ2VkRXhwcmluZ0NvdW50ZG93bnNCeVR5cGVSZXMSHgoGcmVzdWx0",
            "GAEgASgLMg4uc2hhcmVkLlJlc3VsdBIoCgpjb3VudGRvd25zGAIgAygLMhQu",
            "Y291bnRkb3duLkNvdW50ZG93bjK8AwoQQ291bnRkb3duU2VydmljZRJRCg9D",
            "cmVhdGVDb3VudGRvd24SHS5jb3VudGRvd24uQ3JlYXRlQ291bnRkb3duUmVx",
            "Gh0uY291bnRkb3duLkNyZWF0ZUNvdW50ZG93blJlcyIAEm8KGU5leHRDb3Vu",
            "dGRvd25JbnRlcnZhbEJ5SWQSJy5jb3VudGRvd24uTmV4dENvdW50ZG93bklu",
            "dGVydmFsQnlJZFJlcRonLmNvdW50ZG93bi5OZXh0Q291bnRkb3duSW50ZXJ2",
            "YWxCeUlkUmVzIgASWgoSUXVlcnlDb3VudGRvd25CeUlkEiAuY291bnRkb3du",
            "LlF1ZXJ5Q291bnRkb3duQnlJZFJlcRogLmNvdW50ZG93bi5RdWVyeUNvdW50",
            "ZG93bkJ5SWRSZXMiABKHAQohUXVlcnlQYWdlZEV4cHJpbmdDb3VudGRvd25z",
            "QnlUeXBlEi8uY291bnRkb3duLlF1ZXJ5UGFnZWRFeHByaW5nQ291bnRkb3du",
            "c0J5VHlwZVJlcRovLmNvdW50ZG93bi5RdWVyeVBhZ2VkRXhwcmluZ0NvdW50",
            "ZG93bnNCeVR5cGVSZXMiAEKHAQovaW5mby5tb2V0YW5nLnNlcnZpY2Vwcm90",
            "b2NvbC5wcm90b2J1Zi5jb3VudGRvd25CDkNvdW50ZG93blByb3RvUAFaQmdp",
            "dGh1Yi5jb20vbWVpZG9teC9zZXJ2aWNlLXByb3RvY29sL3Byb3RvY29sL3By",
            "b3RvYnVmL2dvL2NvdW50ZG93bmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Shared.ResultReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Countdown.Countdown), global::Countdown.Countdown.Parser, new[]{ "CountdownId", "UserId", "CountdownType", "Title", "Content", "TimeExpired", "TimeLastHandle", "TimeCreated", "TimeUpdated" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Countdown.CreateCountdownReq), global::Countdown.CreateCountdownReq.Parser, new[]{ "UserId", "CountdownType", "Title", "Content", "TimeExpired" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Countdown.CreateCountdownRes), global::Countdown.CreateCountdownRes.Parser, new[]{ "Result", "Countdown" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Countdown.QueryCountdownByIdReq), global::Countdown.QueryCountdownByIdReq.Parser, new[]{ "CountdownId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Countdown.QueryCountdownByIdRes), global::Countdown.QueryCountdownByIdRes.Parser, new[]{ "Result", "Countdown" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Countdown.NextCountdownIntervalByIdReq), global::Countdown.NextCountdownIntervalByIdReq.Parser, new[]{ "CountdownId", "TimeExpired" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Countdown.NextCountdownIntervalByIdRes), global::Countdown.NextCountdownIntervalByIdRes.Parser, new[]{ "Result", "Countdown" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Countdown.QueryPagedExpringCountdownsByTypeReq), global::Countdown.QueryPagedExpringCountdownsByTypeReq.Parser, new[]{ "CountdownType", "Page", "PageSize" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Countdown.QueryPagedExpringCountdownsByTypeRes), global::Countdown.QueryPagedExpringCountdownsByTypeRes.Parser, new[]{ "Result", "Countdowns" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Countdown : pb::IMessage<Countdown>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Countdown> _parser = new pb::MessageParser<Countdown>(() => new Countdown());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Countdown> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Countdown.CountdownReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Countdown() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Countdown(Countdown other) : this() {
      countdownId_ = other.countdownId_;
      userId_ = other.userId_;
      countdownType_ = other.countdownType_;
      title_ = other.title_;
      content_ = other.content_;
      timeExpired_ = other.timeExpired_;
      timeLastHandle_ = other.timeLastHandle_;
      timeCreated_ = other.timeCreated_;
      timeUpdated_ = other.timeUpdated_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Countdown Clone() {
      return new Countdown(this);
    }

    /// <summary>Field number for the "countdown_id" field.</summary>
    public const int CountdownIdFieldNumber = 1;
    private string countdownId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CountdownId {
      get { return countdownId_; }
      set {
        countdownId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 2;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "countdown_type" field.</summary>
    public const int CountdownTypeFieldNumber = 3;
    private string countdownType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CountdownType {
      get { return countdownType_; }
      set {
        countdownType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 11;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 12;
    private string content_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "time_expired" field.</summary>
    public const int TimeExpiredFieldNumber = 21;
    private long timeExpired_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimeExpired {
      get { return timeExpired_; }
      set {
        timeExpired_ = value;
      }
    }

    /// <summary>Field number for the "time_last_handle" field.</summary>
    public const int TimeLastHandleFieldNumber = 22;
    private long timeLastHandle_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimeLastHandle {
      get { return timeLastHandle_; }
      set {
        timeLastHandle_ = value;
      }
    }

    /// <summary>Field number for the "time_created" field.</summary>
    public const int TimeCreatedFieldNumber = 23;
    private long timeCreated_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimeCreated {
      get { return timeCreated_; }
      set {
        timeCreated_ = value;
      }
    }

    /// <summary>Field number for the "time_updated" field.</summary>
    public const int TimeUpdatedFieldNumber = 24;
    private long timeUpdated_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimeUpdated {
      get { return timeUpdated_; }
      set {
        timeUpdated_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Countdown);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Countdown other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CountdownId != other.CountdownId) return false;
      if (UserId != other.UserId) return false;
      if (CountdownType != other.CountdownType) return false;
      if (Title != other.Title) return false;
      if (Content != other.Content) return false;
      if (TimeExpired != other.TimeExpired) return false;
      if (TimeLastHandle != other.TimeLastHandle) return false;
      if (TimeCreated != other.TimeCreated) return false;
      if (TimeUpdated != other.TimeUpdated) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CountdownId.Length != 0) hash ^= CountdownId.GetHashCode();
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (CountdownType.Length != 0) hash ^= CountdownType.GetHashCode();
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (TimeExpired != 0L) hash ^= TimeExpired.GetHashCode();
      if (TimeLastHandle != 0L) hash ^= TimeLastHandle.GetHashCode();
      if (TimeCreated != 0L) hash ^= TimeCreated.GetHashCode();
      if (TimeUpdated != 0L) hash ^= TimeUpdated.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CountdownId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CountdownId);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserId);
      }
      if (CountdownType.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CountdownType);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Title);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Content);
      }
      if (TimeExpired != 0L) {
        output.WriteRawTag(168, 1);
        output.WriteInt64(TimeExpired);
      }
      if (TimeLastHandle != 0L) {
        output.WriteRawTag(176, 1);
        output.WriteInt64(TimeLastHandle);
      }
      if (TimeCreated != 0L) {
        output.WriteRawTag(184, 1);
        output.WriteInt64(TimeCreated);
      }
      if (TimeUpdated != 0L) {
        output.WriteRawTag(192, 1);
        output.WriteInt64(TimeUpdated);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CountdownId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CountdownId);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserId);
      }
      if (CountdownType.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CountdownType);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Title);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Content);
      }
      if (TimeExpired != 0L) {
        output.WriteRawTag(168, 1);
        output.WriteInt64(TimeExpired);
      }
      if (TimeLastHandle != 0L) {
        output.WriteRawTag(176, 1);
        output.WriteInt64(TimeLastHandle);
      }
      if (TimeCreated != 0L) {
        output.WriteRawTag(184, 1);
        output.WriteInt64(TimeCreated);
      }
      if (TimeUpdated != 0L) {
        output.WriteRawTag(192, 1);
        output.WriteInt64(TimeUpdated);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CountdownId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CountdownId);
      }
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (CountdownType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CountdownType);
      }
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (TimeExpired != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(TimeExpired);
      }
      if (TimeLastHandle != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(TimeLastHandle);
      }
      if (TimeCreated != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(TimeCreated);
      }
      if (TimeUpdated != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(TimeUpdated);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Countdown other) {
      if (other == null) {
        return;
      }
      if (other.CountdownId.Length != 0) {
        CountdownId = other.CountdownId;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.CountdownType.Length != 0) {
        CountdownType = other.CountdownType;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      if (other.TimeExpired != 0L) {
        TimeExpired = other.TimeExpired;
      }
      if (other.TimeLastHandle != 0L) {
        TimeLastHandle = other.TimeLastHandle;
      }
      if (other.TimeCreated != 0L) {
        TimeCreated = other.TimeCreated;
      }
      if (other.TimeUpdated != 0L) {
        TimeUpdated = other.TimeUpdated;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CountdownId = input.ReadString();
            break;
          }
          case 18: {
            UserId = input.ReadString();
            break;
          }
          case 26: {
            CountdownType = input.ReadString();
            break;
          }
          case 90: {
            Title = input.ReadString();
            break;
          }
          case 98: {
            Content = input.ReadString();
            break;
          }
          case 168: {
            TimeExpired = input.ReadInt64();
            break;
          }
          case 176: {
            TimeLastHandle = input.ReadInt64();
            break;
          }
          case 184: {
            TimeCreated = input.ReadInt64();
            break;
          }
          case 192: {
            TimeUpdated = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CountdownId = input.ReadString();
            break;
          }
          case 18: {
            UserId = input.ReadString();
            break;
          }
          case 26: {
            CountdownType = input.ReadString();
            break;
          }
          case 90: {
            Title = input.ReadString();
            break;
          }
          case 98: {
            Content = input.ReadString();
            break;
          }
          case 168: {
            TimeExpired = input.ReadInt64();
            break;
          }
          case 176: {
            TimeLastHandle = input.ReadInt64();
            break;
          }
          case 184: {
            TimeCreated = input.ReadInt64();
            break;
          }
          case 192: {
            TimeUpdated = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CreateCountdownReq : pb::IMessage<CreateCountdownReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateCountdownReq> _parser = new pb::MessageParser<CreateCountdownReq>(() => new CreateCountdownReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CreateCountdownReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Countdown.CountdownReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateCountdownReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateCountdownReq(CreateCountdownReq other) : this() {
      userId_ = other.userId_;
      countdownType_ = other.countdownType_;
      title_ = other.title_;
      content_ = other.content_;
      timeExpired_ = other.timeExpired_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateCountdownReq Clone() {
      return new CreateCountdownReq(this);
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 1;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "countdown_type" field.</summary>
    public const int CountdownTypeFieldNumber = 2;
    private string countdownType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CountdownType {
      get { return countdownType_; }
      set {
        countdownType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 11;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 12;
    private string content_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "time_expired" field.</summary>
    public const int TimeExpiredFieldNumber = 21;
    private long timeExpired_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimeExpired {
      get { return timeExpired_; }
      set {
        timeExpired_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CreateCountdownReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CreateCountdownReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (CountdownType != other.CountdownType) return false;
      if (Title != other.Title) return false;
      if (Content != other.Content) return false;
      if (TimeExpired != other.TimeExpired) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (CountdownType.Length != 0) hash ^= CountdownType.GetHashCode();
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (TimeExpired != 0L) hash ^= TimeExpired.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (CountdownType.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CountdownType);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Title);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Content);
      }
      if (TimeExpired != 0L) {
        output.WriteRawTag(168, 1);
        output.WriteInt64(TimeExpired);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (CountdownType.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CountdownType);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Title);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Content);
      }
      if (TimeExpired != 0L) {
        output.WriteRawTag(168, 1);
        output.WriteInt64(TimeExpired);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (CountdownType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CountdownType);
      }
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (TimeExpired != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(TimeExpired);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CreateCountdownReq other) {
      if (other == null) {
        return;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.CountdownType.Length != 0) {
        CountdownType = other.CountdownType;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      if (other.TimeExpired != 0L) {
        TimeExpired = other.TimeExpired;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 18: {
            CountdownType = input.ReadString();
            break;
          }
          case 90: {
            Title = input.ReadString();
            break;
          }
          case 98: {
            Content = input.ReadString();
            break;
          }
          case 168: {
            TimeExpired = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 18: {
            CountdownType = input.ReadString();
            break;
          }
          case 90: {
            Title = input.ReadString();
            break;
          }
          case 98: {
            Content = input.ReadString();
            break;
          }
          case 168: {
            TimeExpired = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CreateCountdownRes : pb::IMessage<CreateCountdownRes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateCountdownRes> _parser = new pb::MessageParser<CreateCountdownRes>(() => new CreateCountdownRes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CreateCountdownRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Countdown.CountdownReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateCountdownRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateCountdownRes(CreateCountdownRes other) : this() {
      result_ = other.result_ != null ? other.result_.Clone() : null;
      countdown_ = other.countdown_ != null ? other.countdown_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateCountdownRes Clone() {
      return new CreateCountdownRes(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::Shared.Result result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Shared.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "countdown" field.</summary>
    public const int CountdownFieldNumber = 2;
    private global::Countdown.Countdown countdown_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Countdown.Countdown Countdown {
      get { return countdown_; }
      set {
        countdown_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CreateCountdownRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CreateCountdownRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Result, other.Result)) return false;
      if (!object.Equals(Countdown, other.Countdown)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (result_ != null) hash ^= Result.GetHashCode();
      if (countdown_ != null) hash ^= Countdown.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      if (countdown_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Countdown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      if (countdown_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Countdown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      if (countdown_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Countdown);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CreateCountdownRes other) {
      if (other == null) {
        return;
      }
      if (other.result_ != null) {
        if (result_ == null) {
          Result = new global::Shared.Result();
        }
        Result.MergeFrom(other.Result);
      }
      if (other.countdown_ != null) {
        if (countdown_ == null) {
          Countdown = new global::Countdown.Countdown();
        }
        Countdown.MergeFrom(other.Countdown);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::Shared.Result();
            }
            input.ReadMessage(Result);
            break;
          }
          case 18: {
            if (countdown_ == null) {
              Countdown = new global::Countdown.Countdown();
            }
            input.ReadMessage(Countdown);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::Shared.Result();
            }
            input.ReadMessage(Result);
            break;
          }
          case 18: {
            if (countdown_ == null) {
              Countdown = new global::Countdown.Countdown();
            }
            input.ReadMessage(Countdown);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class QueryCountdownByIdReq : pb::IMessage<QueryCountdownByIdReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QueryCountdownByIdReq> _parser = new pb::MessageParser<QueryCountdownByIdReq>(() => new QueryCountdownByIdReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QueryCountdownByIdReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Countdown.CountdownReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryCountdownByIdReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryCountdownByIdReq(QueryCountdownByIdReq other) : this() {
      countdownId_ = other.countdownId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryCountdownByIdReq Clone() {
      return new QueryCountdownByIdReq(this);
    }

    /// <summary>Field number for the "countdown_id" field.</summary>
    public const int CountdownIdFieldNumber = 1;
    private string countdownId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CountdownId {
      get { return countdownId_; }
      set {
        countdownId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QueryCountdownByIdReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QueryCountdownByIdReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CountdownId != other.CountdownId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CountdownId.Length != 0) hash ^= CountdownId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CountdownId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CountdownId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CountdownId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CountdownId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CountdownId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CountdownId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QueryCountdownByIdReq other) {
      if (other == null) {
        return;
      }
      if (other.CountdownId.Length != 0) {
        CountdownId = other.CountdownId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CountdownId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CountdownId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class QueryCountdownByIdRes : pb::IMessage<QueryCountdownByIdRes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QueryCountdownByIdRes> _parser = new pb::MessageParser<QueryCountdownByIdRes>(() => new QueryCountdownByIdRes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QueryCountdownByIdRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Countdown.CountdownReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryCountdownByIdRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryCountdownByIdRes(QueryCountdownByIdRes other) : this() {
      result_ = other.result_ != null ? other.result_.Clone() : null;
      countdown_ = other.countdown_ != null ? other.countdown_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryCountdownByIdRes Clone() {
      return new QueryCountdownByIdRes(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::Shared.Result result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Shared.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "countdown" field.</summary>
    public const int CountdownFieldNumber = 2;
    private global::Countdown.Countdown countdown_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Countdown.Countdown Countdown {
      get { return countdown_; }
      set {
        countdown_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QueryCountdownByIdRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QueryCountdownByIdRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Result, other.Result)) return false;
      if (!object.Equals(Countdown, other.Countdown)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (result_ != null) hash ^= Result.GetHashCode();
      if (countdown_ != null) hash ^= Countdown.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      if (countdown_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Countdown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      if (countdown_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Countdown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      if (countdown_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Countdown);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QueryCountdownByIdRes other) {
      if (other == null) {
        return;
      }
      if (other.result_ != null) {
        if (result_ == null) {
          Result = new global::Shared.Result();
        }
        Result.MergeFrom(other.Result);
      }
      if (other.countdown_ != null) {
        if (countdown_ == null) {
          Countdown = new global::Countdown.Countdown();
        }
        Countdown.MergeFrom(other.Countdown);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::Shared.Result();
            }
            input.ReadMessage(Result);
            break;
          }
          case 18: {
            if (countdown_ == null) {
              Countdown = new global::Countdown.Countdown();
            }
            input.ReadMessage(Countdown);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::Shared.Result();
            }
            input.ReadMessage(Result);
            break;
          }
          case 18: {
            if (countdown_ == null) {
              Countdown = new global::Countdown.Countdown();
            }
            input.ReadMessage(Countdown);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class NextCountdownIntervalByIdReq : pb::IMessage<NextCountdownIntervalByIdReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NextCountdownIntervalByIdReq> _parser = new pb::MessageParser<NextCountdownIntervalByIdReq>(() => new NextCountdownIntervalByIdReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NextCountdownIntervalByIdReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Countdown.CountdownReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NextCountdownIntervalByIdReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NextCountdownIntervalByIdReq(NextCountdownIntervalByIdReq other) : this() {
      countdownId_ = other.countdownId_;
      timeExpired_ = other.timeExpired_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NextCountdownIntervalByIdReq Clone() {
      return new NextCountdownIntervalByIdReq(this);
    }

    /// <summary>Field number for the "countdown_id" field.</summary>
    public const int CountdownIdFieldNumber = 1;
    private string countdownId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CountdownId {
      get { return countdownId_; }
      set {
        countdownId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "time_expired" field.</summary>
    public const int TimeExpiredFieldNumber = 2;
    private long timeExpired_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimeExpired {
      get { return timeExpired_; }
      set {
        timeExpired_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NextCountdownIntervalByIdReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NextCountdownIntervalByIdReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CountdownId != other.CountdownId) return false;
      if (TimeExpired != other.TimeExpired) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CountdownId.Length != 0) hash ^= CountdownId.GetHashCode();
      if (TimeExpired != 0L) hash ^= TimeExpired.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CountdownId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CountdownId);
      }
      if (TimeExpired != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TimeExpired);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CountdownId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CountdownId);
      }
      if (TimeExpired != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TimeExpired);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CountdownId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CountdownId);
      }
      if (TimeExpired != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimeExpired);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NextCountdownIntervalByIdReq other) {
      if (other == null) {
        return;
      }
      if (other.CountdownId.Length != 0) {
        CountdownId = other.CountdownId;
      }
      if (other.TimeExpired != 0L) {
        TimeExpired = other.TimeExpired;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CountdownId = input.ReadString();
            break;
          }
          case 16: {
            TimeExpired = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CountdownId = input.ReadString();
            break;
          }
          case 16: {
            TimeExpired = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class NextCountdownIntervalByIdRes : pb::IMessage<NextCountdownIntervalByIdRes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NextCountdownIntervalByIdRes> _parser = new pb::MessageParser<NextCountdownIntervalByIdRes>(() => new NextCountdownIntervalByIdRes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NextCountdownIntervalByIdRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Countdown.CountdownReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NextCountdownIntervalByIdRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NextCountdownIntervalByIdRes(NextCountdownIntervalByIdRes other) : this() {
      result_ = other.result_ != null ? other.result_.Clone() : null;
      countdown_ = other.countdown_ != null ? other.countdown_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NextCountdownIntervalByIdRes Clone() {
      return new NextCountdownIntervalByIdRes(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::Shared.Result result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Shared.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "countdown" field.</summary>
    public const int CountdownFieldNumber = 2;
    private global::Countdown.Countdown countdown_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Countdown.Countdown Countdown {
      get { return countdown_; }
      set {
        countdown_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NextCountdownIntervalByIdRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NextCountdownIntervalByIdRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Result, other.Result)) return false;
      if (!object.Equals(Countdown, other.Countdown)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (result_ != null) hash ^= Result.GetHashCode();
      if (countdown_ != null) hash ^= Countdown.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      if (countdown_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Countdown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      if (countdown_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Countdown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      if (countdown_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Countdown);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NextCountdownIntervalByIdRes other) {
      if (other == null) {
        return;
      }
      if (other.result_ != null) {
        if (result_ == null) {
          Result = new global::Shared.Result();
        }
        Result.MergeFrom(other.Result);
      }
      if (other.countdown_ != null) {
        if (countdown_ == null) {
          Countdown = new global::Countdown.Countdown();
        }
        Countdown.MergeFrom(other.Countdown);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::Shared.Result();
            }
            input.ReadMessage(Result);
            break;
          }
          case 18: {
            if (countdown_ == null) {
              Countdown = new global::Countdown.Countdown();
            }
            input.ReadMessage(Countdown);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::Shared.Result();
            }
            input.ReadMessage(Result);
            break;
          }
          case 18: {
            if (countdown_ == null) {
              Countdown = new global::Countdown.Countdown();
            }
            input.ReadMessage(Countdown);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class QueryPagedExpringCountdownsByTypeReq : pb::IMessage<QueryPagedExpringCountdownsByTypeReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QueryPagedExpringCountdownsByTypeReq> _parser = new pb::MessageParser<QueryPagedExpringCountdownsByTypeReq>(() => new QueryPagedExpringCountdownsByTypeReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QueryPagedExpringCountdownsByTypeReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Countdown.CountdownReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryPagedExpringCountdownsByTypeReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryPagedExpringCountdownsByTypeReq(QueryPagedExpringCountdownsByTypeReq other) : this() {
      countdownType_ = other.countdownType_;
      page_ = other.page_;
      pageSize_ = other.pageSize_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryPagedExpringCountdownsByTypeReq Clone() {
      return new QueryPagedExpringCountdownsByTypeReq(this);
    }

    /// <summary>Field number for the "countdown_type" field.</summary>
    public const int CountdownTypeFieldNumber = 1;
    private string countdownType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CountdownType {
      get { return countdownType_; }
      set {
        countdownType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "page" field.</summary>
    public const int PageFieldNumber = 2;
    private long page_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Page {
      get { return page_; }
      set {
        page_ = value;
      }
    }

    /// <summary>Field number for the "page_size" field.</summary>
    public const int PageSizeFieldNumber = 3;
    private long pageSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PageSize {
      get { return pageSize_; }
      set {
        pageSize_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QueryPagedExpringCountdownsByTypeReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QueryPagedExpringCountdownsByTypeReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CountdownType != other.CountdownType) return false;
      if (Page != other.Page) return false;
      if (PageSize != other.PageSize) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CountdownType.Length != 0) hash ^= CountdownType.GetHashCode();
      if (Page != 0L) hash ^= Page.GetHashCode();
      if (PageSize != 0L) hash ^= PageSize.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CountdownType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CountdownType);
      }
      if (Page != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Page);
      }
      if (PageSize != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(PageSize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CountdownType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CountdownType);
      }
      if (Page != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Page);
      }
      if (PageSize != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(PageSize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CountdownType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CountdownType);
      }
      if (Page != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Page);
      }
      if (PageSize != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PageSize);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QueryPagedExpringCountdownsByTypeReq other) {
      if (other == null) {
        return;
      }
      if (other.CountdownType.Length != 0) {
        CountdownType = other.CountdownType;
      }
      if (other.Page != 0L) {
        Page = other.Page;
      }
      if (other.PageSize != 0L) {
        PageSize = other.PageSize;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CountdownType = input.ReadString();
            break;
          }
          case 16: {
            Page = input.ReadInt64();
            break;
          }
          case 24: {
            PageSize = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CountdownType = input.ReadString();
            break;
          }
          case 16: {
            Page = input.ReadInt64();
            break;
          }
          case 24: {
            PageSize = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class QueryPagedExpringCountdownsByTypeRes : pb::IMessage<QueryPagedExpringCountdownsByTypeRes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QueryPagedExpringCountdownsByTypeRes> _parser = new pb::MessageParser<QueryPagedExpringCountdownsByTypeRes>(() => new QueryPagedExpringCountdownsByTypeRes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QueryPagedExpringCountdownsByTypeRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Countdown.CountdownReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryPagedExpringCountdownsByTypeRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryPagedExpringCountdownsByTypeRes(QueryPagedExpringCountdownsByTypeRes other) : this() {
      result_ = other.result_ != null ? other.result_.Clone() : null;
      countdowns_ = other.countdowns_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryPagedExpringCountdownsByTypeRes Clone() {
      return new QueryPagedExpringCountdownsByTypeRes(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::Shared.Result result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Shared.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "countdowns" field.</summary>
    public const int CountdownsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Countdown.Countdown> _repeated_countdowns_codec
        = pb::FieldCodec.ForMessage(18, global::Countdown.Countdown.Parser);
    private readonly pbc::RepeatedField<global::Countdown.Countdown> countdowns_ = new pbc::RepeatedField<global::Countdown.Countdown>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Countdown.Countdown> Countdowns {
      get { return countdowns_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QueryPagedExpringCountdownsByTypeRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QueryPagedExpringCountdownsByTypeRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Result, other.Result)) return false;
      if(!countdowns_.Equals(other.countdowns_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (result_ != null) hash ^= Result.GetHashCode();
      hash ^= countdowns_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      countdowns_.WriteTo(output, _repeated_countdowns_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      countdowns_.WriteTo(ref output, _repeated_countdowns_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      size += countdowns_.CalculateSize(_repeated_countdowns_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QueryPagedExpringCountdownsByTypeRes other) {
      if (other == null) {
        return;
      }
      if (other.result_ != null) {
        if (result_ == null) {
          Result = new global::Shared.Result();
        }
        Result.MergeFrom(other.Result);
      }
      countdowns_.Add(other.countdowns_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::Shared.Result();
            }
            input.ReadMessage(Result);
            break;
          }
          case 18: {
            countdowns_.AddEntriesFrom(input, _repeated_countdowns_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::Shared.Result();
            }
            input.ReadMessage(Result);
            break;
          }
          case 18: {
            countdowns_.AddEntriesFrom(ref input, _repeated_countdowns_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
