// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: note/note.proto

package info.moetang.serviceprotocol.protobuf.note;

public interface UpdateNoteByIdResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:note.UpdateNoteByIdRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.shared.Result result = 1;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <code>.shared.Result result = 1;</code>
   * @return The result.
   */
  info.moetang.serviceprotocol.protobuf.shared.Result getResult();
  /**
   * <code>.shared.Result result = 1;</code>
   */
  info.moetang.serviceprotocol.protobuf.shared.ResultOrBuilder getResultOrBuilder();

  /**
   * <code>.note.Note note = 2;</code>
   * @return Whether the note field is set.
   */
  boolean hasNote();
  /**
   * <code>.note.Note note = 2;</code>
   * @return The note.
   */
  info.moetang.serviceprotocol.protobuf.note.Note getNote();
  /**
   * <code>.note.Note note = 2;</code>
   */
  info.moetang.serviceprotocol.protobuf.note.NoteOrBuilder getNoteOrBuilder();
}
