// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forum/forum.proto

package info.moetang.serviceprotocol.protobuf.forum;

public interface DeleteReplyByIdReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:forum.DeleteReplyByIdReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reply_id = 1;</code>
   * @return The replyId.
   */
  java.lang.String getReplyId();
  /**
   * <code>string reply_id = 1;</code>
   * @return The bytes for replyId.
   */
  com.google.protobuf.ByteString
      getReplyIdBytes();
}
