// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forum/forum.proto

package info.moetang.serviceprotocol.protobuf.forum;

public interface ForumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:forum.Forum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string forum_id = 1;</code>
   * @return The forumId.
   */
  java.lang.String getForumId();
  /**
   * <code>string forum_id = 1;</code>
   * @return The bytes for forumId.
   */
  com.google.protobuf.ByteString
      getForumIdBytes();

  /**
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string forum_name = 11;</code>
   * @return The forumName.
   */
  java.lang.String getForumName();
  /**
   * <code>string forum_name = 11;</code>
   * @return The bytes for forumName.
   */
  com.google.protobuf.ByteString
      getForumNameBytes();

  /**
   * <code>string forum_description = 12;</code>
   * @return The forumDescription.
   */
  java.lang.String getForumDescription();
  /**
   * <code>string forum_description = 12;</code>
   * @return The bytes for forumDescription.
   */
  com.google.protobuf.ByteString
      getForumDescriptionBytes();

  /**
   * <code>int64 time_created = 21;</code>
   * @return The timeCreated.
   */
  long getTimeCreated();

  /**
   * <code>int64 time_updated = 22;</code>
   * @return The timeUpdated.
   */
  long getTimeUpdated();
}
