// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forum/forum.proto

package info.moetang.serviceprotocol.protobuf.forum;

/**
 * Protobuf type {@code forum.ThreadLite}
 */
public final class ThreadLite extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:forum.ThreadLite)
    ThreadLiteOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ThreadLite.newBuilder() to construct.
  private ThreadLite(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ThreadLite() {
    threadId_ = "";
    forumId_ = "";
    userId_ = "";
    threadTitle_ = "";
    threadContent_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ThreadLite();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ThreadLite(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            threadId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            forumId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            threadTitle_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            threadContent_ = s;
            break;
          }
          case 168: {

            timeCreated_ = input.readInt64();
            break;
          }
          case 176: {

            timeUpdated_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.moetang.serviceprotocol.protobuf.forum.ForumProto.internal_static_forum_ThreadLite_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.moetang.serviceprotocol.protobuf.forum.ForumProto.internal_static_forum_ThreadLite_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.moetang.serviceprotocol.protobuf.forum.ThreadLite.class, info.moetang.serviceprotocol.protobuf.forum.ThreadLite.Builder.class);
  }

  public static final int THREAD_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object threadId_;
  /**
   * <code>string thread_id = 1;</code>
   * @return The threadId.
   */
  @java.lang.Override
  public java.lang.String getThreadId() {
    java.lang.Object ref = threadId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      threadId_ = s;
      return s;
    }
  }
  /**
   * <code>string thread_id = 1;</code>
   * @return The bytes for threadId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getThreadIdBytes() {
    java.lang.Object ref = threadId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      threadId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FORUM_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object forumId_;
  /**
   * <code>string forum_id = 2;</code>
   * @return The forumId.
   */
  @java.lang.Override
  public java.lang.String getForumId() {
    java.lang.Object ref = forumId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      forumId_ = s;
      return s;
    }
  }
  /**
   * <code>string forum_id = 2;</code>
   * @return The bytes for forumId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getForumIdBytes() {
    java.lang.Object ref = forumId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      forumId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object userId_;
  /**
   * <code>string user_id = 3;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string user_id = 3;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int THREAD_TITLE_FIELD_NUMBER = 11;
  private volatile java.lang.Object threadTitle_;
  /**
   * <code>string thread_title = 11;</code>
   * @return The threadTitle.
   */
  @java.lang.Override
  public java.lang.String getThreadTitle() {
    java.lang.Object ref = threadTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      threadTitle_ = s;
      return s;
    }
  }
  /**
   * <code>string thread_title = 11;</code>
   * @return The bytes for threadTitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getThreadTitleBytes() {
    java.lang.Object ref = threadTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      threadTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int THREAD_CONTENT_FIELD_NUMBER = 12;
  private volatile java.lang.Object threadContent_;
  /**
   * <code>string thread_content = 12;</code>
   * @return The threadContent.
   */
  @java.lang.Override
  public java.lang.String getThreadContent() {
    java.lang.Object ref = threadContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      threadContent_ = s;
      return s;
    }
  }
  /**
   * <code>string thread_content = 12;</code>
   * @return The bytes for threadContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getThreadContentBytes() {
    java.lang.Object ref = threadContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      threadContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_CREATED_FIELD_NUMBER = 21;
  private long timeCreated_;
  /**
   * <code>int64 time_created = 21;</code>
   * @return The timeCreated.
   */
  @java.lang.Override
  public long getTimeCreated() {
    return timeCreated_;
  }

  public static final int TIME_UPDATED_FIELD_NUMBER = 22;
  private long timeUpdated_;
  /**
   * <code>int64 time_updated = 22;</code>
   * @return The timeUpdated.
   */
  @java.lang.Override
  public long getTimeUpdated() {
    return timeUpdated_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getThreadIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, threadId_);
    }
    if (!getForumIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, forumId_);
    }
    if (!getUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userId_);
    }
    if (!getThreadTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, threadTitle_);
    }
    if (!getThreadContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, threadContent_);
    }
    if (timeCreated_ != 0L) {
      output.writeInt64(21, timeCreated_);
    }
    if (timeUpdated_ != 0L) {
      output.writeInt64(22, timeUpdated_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getThreadIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, threadId_);
    }
    if (!getForumIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, forumId_);
    }
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userId_);
    }
    if (!getThreadTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, threadTitle_);
    }
    if (!getThreadContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, threadContent_);
    }
    if (timeCreated_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(21, timeCreated_);
    }
    if (timeUpdated_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(22, timeUpdated_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.moetang.serviceprotocol.protobuf.forum.ThreadLite)) {
      return super.equals(obj);
    }
    info.moetang.serviceprotocol.protobuf.forum.ThreadLite other = (info.moetang.serviceprotocol.protobuf.forum.ThreadLite) obj;

    if (!getThreadId()
        .equals(other.getThreadId())) return false;
    if (!getForumId()
        .equals(other.getForumId())) return false;
    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!getThreadTitle()
        .equals(other.getThreadTitle())) return false;
    if (!getThreadContent()
        .equals(other.getThreadContent())) return false;
    if (getTimeCreated()
        != other.getTimeCreated()) return false;
    if (getTimeUpdated()
        != other.getTimeUpdated()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + THREAD_ID_FIELD_NUMBER;
    hash = (53 * hash) + getThreadId().hashCode();
    hash = (37 * hash) + FORUM_ID_FIELD_NUMBER;
    hash = (53 * hash) + getForumId().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + THREAD_TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getThreadTitle().hashCode();
    hash = (37 * hash) + THREAD_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getThreadContent().hashCode();
    hash = (37 * hash) + TIME_CREATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeCreated());
    hash = (37 * hash) + TIME_UPDATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeUpdated());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.moetang.serviceprotocol.protobuf.forum.ThreadLite parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.moetang.serviceprotocol.protobuf.forum.ThreadLite parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.moetang.serviceprotocol.protobuf.forum.ThreadLite parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.moetang.serviceprotocol.protobuf.forum.ThreadLite parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.moetang.serviceprotocol.protobuf.forum.ThreadLite parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.moetang.serviceprotocol.protobuf.forum.ThreadLite parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.moetang.serviceprotocol.protobuf.forum.ThreadLite parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.moetang.serviceprotocol.protobuf.forum.ThreadLite parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.moetang.serviceprotocol.protobuf.forum.ThreadLite parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.moetang.serviceprotocol.protobuf.forum.ThreadLite parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.moetang.serviceprotocol.protobuf.forum.ThreadLite parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.moetang.serviceprotocol.protobuf.forum.ThreadLite parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.moetang.serviceprotocol.protobuf.forum.ThreadLite prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code forum.ThreadLite}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:forum.ThreadLite)
      info.moetang.serviceprotocol.protobuf.forum.ThreadLiteOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.moetang.serviceprotocol.protobuf.forum.ForumProto.internal_static_forum_ThreadLite_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.moetang.serviceprotocol.protobuf.forum.ForumProto.internal_static_forum_ThreadLite_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.moetang.serviceprotocol.protobuf.forum.ThreadLite.class, info.moetang.serviceprotocol.protobuf.forum.ThreadLite.Builder.class);
    }

    // Construct using info.moetang.serviceprotocol.protobuf.forum.ThreadLite.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      threadId_ = "";

      forumId_ = "";

      userId_ = "";

      threadTitle_ = "";

      threadContent_ = "";

      timeCreated_ = 0L;

      timeUpdated_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.moetang.serviceprotocol.protobuf.forum.ForumProto.internal_static_forum_ThreadLite_descriptor;
    }

    @java.lang.Override
    public info.moetang.serviceprotocol.protobuf.forum.ThreadLite getDefaultInstanceForType() {
      return info.moetang.serviceprotocol.protobuf.forum.ThreadLite.getDefaultInstance();
    }

    @java.lang.Override
    public info.moetang.serviceprotocol.protobuf.forum.ThreadLite build() {
      info.moetang.serviceprotocol.protobuf.forum.ThreadLite result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.moetang.serviceprotocol.protobuf.forum.ThreadLite buildPartial() {
      info.moetang.serviceprotocol.protobuf.forum.ThreadLite result = new info.moetang.serviceprotocol.protobuf.forum.ThreadLite(this);
      result.threadId_ = threadId_;
      result.forumId_ = forumId_;
      result.userId_ = userId_;
      result.threadTitle_ = threadTitle_;
      result.threadContent_ = threadContent_;
      result.timeCreated_ = timeCreated_;
      result.timeUpdated_ = timeUpdated_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.moetang.serviceprotocol.protobuf.forum.ThreadLite) {
        return mergeFrom((info.moetang.serviceprotocol.protobuf.forum.ThreadLite)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.moetang.serviceprotocol.protobuf.forum.ThreadLite other) {
      if (other == info.moetang.serviceprotocol.protobuf.forum.ThreadLite.getDefaultInstance()) return this;
      if (!other.getThreadId().isEmpty()) {
        threadId_ = other.threadId_;
        onChanged();
      }
      if (!other.getForumId().isEmpty()) {
        forumId_ = other.forumId_;
        onChanged();
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (!other.getThreadTitle().isEmpty()) {
        threadTitle_ = other.threadTitle_;
        onChanged();
      }
      if (!other.getThreadContent().isEmpty()) {
        threadContent_ = other.threadContent_;
        onChanged();
      }
      if (other.getTimeCreated() != 0L) {
        setTimeCreated(other.getTimeCreated());
      }
      if (other.getTimeUpdated() != 0L) {
        setTimeUpdated(other.getTimeUpdated());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      info.moetang.serviceprotocol.protobuf.forum.ThreadLite parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (info.moetang.serviceprotocol.protobuf.forum.ThreadLite) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object threadId_ = "";
    /**
     * <code>string thread_id = 1;</code>
     * @return The threadId.
     */
    public java.lang.String getThreadId() {
      java.lang.Object ref = threadId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        threadId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string thread_id = 1;</code>
     * @return The bytes for threadId.
     */
    public com.google.protobuf.ByteString
        getThreadIdBytes() {
      java.lang.Object ref = threadId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        threadId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string thread_id = 1;</code>
     * @param value The threadId to set.
     * @return This builder for chaining.
     */
    public Builder setThreadId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      threadId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string thread_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearThreadId() {
      
      threadId_ = getDefaultInstance().getThreadId();
      onChanged();
      return this;
    }
    /**
     * <code>string thread_id = 1;</code>
     * @param value The bytes for threadId to set.
     * @return This builder for chaining.
     */
    public Builder setThreadIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      threadId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object forumId_ = "";
    /**
     * <code>string forum_id = 2;</code>
     * @return The forumId.
     */
    public java.lang.String getForumId() {
      java.lang.Object ref = forumId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        forumId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string forum_id = 2;</code>
     * @return The bytes for forumId.
     */
    public com.google.protobuf.ByteString
        getForumIdBytes() {
      java.lang.Object ref = forumId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        forumId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string forum_id = 2;</code>
     * @param value The forumId to set.
     * @return This builder for chaining.
     */
    public Builder setForumId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      forumId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string forum_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearForumId() {
      
      forumId_ = getDefaultInstance().getForumId();
      onChanged();
      return this;
    }
    /**
     * <code>string forum_id = 2;</code>
     * @param value The bytes for forumId to set.
     * @return This builder for chaining.
     */
    public Builder setForumIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      forumId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <code>string user_id = 3;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_id = 3;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_id = 3;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 3;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object threadTitle_ = "";
    /**
     * <code>string thread_title = 11;</code>
     * @return The threadTitle.
     */
    public java.lang.String getThreadTitle() {
      java.lang.Object ref = threadTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        threadTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string thread_title = 11;</code>
     * @return The bytes for threadTitle.
     */
    public com.google.protobuf.ByteString
        getThreadTitleBytes() {
      java.lang.Object ref = threadTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        threadTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string thread_title = 11;</code>
     * @param value The threadTitle to set.
     * @return This builder for chaining.
     */
    public Builder setThreadTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      threadTitle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string thread_title = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearThreadTitle() {
      
      threadTitle_ = getDefaultInstance().getThreadTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string thread_title = 11;</code>
     * @param value The bytes for threadTitle to set.
     * @return This builder for chaining.
     */
    public Builder setThreadTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      threadTitle_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object threadContent_ = "";
    /**
     * <code>string thread_content = 12;</code>
     * @return The threadContent.
     */
    public java.lang.String getThreadContent() {
      java.lang.Object ref = threadContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        threadContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string thread_content = 12;</code>
     * @return The bytes for threadContent.
     */
    public com.google.protobuf.ByteString
        getThreadContentBytes() {
      java.lang.Object ref = threadContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        threadContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string thread_content = 12;</code>
     * @param value The threadContent to set.
     * @return This builder for chaining.
     */
    public Builder setThreadContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      threadContent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string thread_content = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearThreadContent() {
      
      threadContent_ = getDefaultInstance().getThreadContent();
      onChanged();
      return this;
    }
    /**
     * <code>string thread_content = 12;</code>
     * @param value The bytes for threadContent to set.
     * @return This builder for chaining.
     */
    public Builder setThreadContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      threadContent_ = value;
      onChanged();
      return this;
    }

    private long timeCreated_ ;
    /**
     * <code>int64 time_created = 21;</code>
     * @return The timeCreated.
     */
    @java.lang.Override
    public long getTimeCreated() {
      return timeCreated_;
    }
    /**
     * <code>int64 time_created = 21;</code>
     * @param value The timeCreated to set.
     * @return This builder for chaining.
     */
    public Builder setTimeCreated(long value) {
      
      timeCreated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 time_created = 21;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeCreated() {
      
      timeCreated_ = 0L;
      onChanged();
      return this;
    }

    private long timeUpdated_ ;
    /**
     * <code>int64 time_updated = 22;</code>
     * @return The timeUpdated.
     */
    @java.lang.Override
    public long getTimeUpdated() {
      return timeUpdated_;
    }
    /**
     * <code>int64 time_updated = 22;</code>
     * @param value The timeUpdated to set.
     * @return This builder for chaining.
     */
    public Builder setTimeUpdated(long value) {
      
      timeUpdated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 time_updated = 22;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeUpdated() {
      
      timeUpdated_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:forum.ThreadLite)
  }

  // @@protoc_insertion_point(class_scope:forum.ThreadLite)
  private static final info.moetang.serviceprotocol.protobuf.forum.ThreadLite DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.moetang.serviceprotocol.protobuf.forum.ThreadLite();
  }

  public static info.moetang.serviceprotocol.protobuf.forum.ThreadLite getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ThreadLite>
      PARSER = new com.google.protobuf.AbstractParser<ThreadLite>() {
    @java.lang.Override
    public ThreadLite parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ThreadLite(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ThreadLite> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ThreadLite> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.moetang.serviceprotocol.protobuf.forum.ThreadLite getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

